name: unitdb_client
description: Lightweight and high performance publish-subscribe messaging system - dart client library.
version: 0.1.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  async: ^2.4.2
  grpc: ^3.0.0
  protobuf: ^2.0.0
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.8.0
  build_web_compilers: ^2.8.0
